# frozen_string_literal: true

source "https://rubygems.org"

gem "dotenv", "~> 3.1"

gem "http", "~> 5.2"

gem 'ostruct'

gem "thor", "~> 1.3"

gem "terminal-table", "~> 3.0"

gem "webmock", "~> 3.24"

gem "rspec", "~> 3.12"
